### Create a new user
POST http://localhost:3000/authentication/sign-up
Content-Type:application/json

{
  "firstName": "Bobby",
  "lastName": "Ross",
  "email": "bob@ross6.com",
  "password": "12345678"
}

### Sign In user
POST http://localhost:3000/authentication/sign-in
Content-Type:application/json

{
  "email": "bob@ross6.com",
  "password": "12345678"
}

### Get all users
GET http://localhost:3000/user

### Get user by ID
GET http://localhost:3000/user/8

### Update user
PUT http://localhost:3000/user/8
Content-Type:application/json

{
  "firstName": "Bob",
  "lastName": "Ross"
}

### Delete user
DELETE http://localhost:3000/user/8