### Get current user profile
GET {{url}}/user/profile
Authorization: Bearer {{accessToken}}

### Search users
GET {{url}}/user
Authorization: Bearer {{accessToken}}

### Get user by ID
GET {{url}}/user/8
Authorization: Bearer {{accessToken}}

### Update user
PUT {{url}}/user/18
Content-Type:application/json
Authorization: Bearer {{accessToken}}

{
  "firstName": "First",
  "lastName": "Last",
  "role": "admin"
}

### Delete user
DELETE {{url}}/user/6
Authorization: Bearer {{accessToken}}